const ActionTypes = {
	SIGN_IN_USER: 'SIGN_IN_USER',
	AUTH_USER: 'AUTH_USER',
	AUTH_ERROR: 'AUTH_ERROR',
	SIGN_OUT_USER: 'SIGN_OUT_USER',
	SIGN_UP_USER: 'SIGN_UP_USER',
	FETCH_MESSAGE: 'FETCH_MESSAGE'
};

export default ActionTypes;
